### ISSUE TITLE
Is possible to open API access to the backend server

### ISSUE THREAD

**Issue by mmesojedec** [lucideus-repo/UnSAFE_Bank#13]
Hi,

Is there a simple way to open API access to backend server or UnSAFE Bank is not build to allow API access?

Thanks,
Miha

**Comment by mmesojedec** [comment]
Hi,

Is possible to get answer for this question?

thanks,
Miha

**Comment by snazzysanoj** [comment]
@mmesojedec By default, all APIs are exposed over port 80
