### ISSUE TITLE
Web failed to built

### ISSUE THREAD

**Issue by arifkyi** [lucideus-repo/UnSAFE_Bank#33]
Hello,

Im using MacOs Monterey 12.4

 **docker version**
Client:
 Cloud integration: v1.0.25
 Version:           20.10.16
 API version:       1.41
 Go version:        go1.17.10
 Git commit:        aa7e414
 Built:             Thu May 12 09:20:34 2022
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

**Server: Docker Desktop 4.9.1 (81317)**
 Engine:
  Version:          20.10.16
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.10
  Git commit:       f756502
  Built:            Thu May 12 09:15:42 2022

i got this error  after run **docker-compose up -d**  below, need your kindly help for the resolution:

=> => extracting sha256:ba036c7f95ecc063c84fbe789765b97feefdbc331a31abf9  0.0s
 => => extracting sha256:a46fd6a16a7c6563c064f8ad9197db0bcf1191095cc3af29  0.0s
 => [internal] load build context                                          0.4s
 => => transferring context: 11.59MB                                       0.4s
 => [build 2/5] WORKDIR /app                                               0.3s
 => [build 3/5] COPY . /app                                                0.1s
 => ERROR [build 4/5] RUN yarn -s                                         59.9s
------
 > [build 4/5] RUN yarn -s:
#12 0.831 warning Pattern ["redux-thunk@latest"] is trying to unpack in the same destination "/usr/local/share/.cache/yarn/v6/npm-redux-thunk-2.3.0-51c2c19a185ed5187aaa9a2d08b666d0d6467622-integrity/node_modules/redux-thunk" as pattern ["redux-thunk@^2.3.0"]. This could result in non-deterministic behavior, skipping.
#12 38.74 warning " > bootstrap@4.5.3" has unmet peer dependency "jquery@1.9.1 - 3".
#12 38.74 warning " > bootstrap@4.5.3" has unmet peer dependency "popper.js@^1.16.1".
#12 38.74 warning " > react-idle-timer@4.5.0" has unmet peer dependency "prop-types@>=15".
#12 38.74 warning " > @testing-library/user-event@7.2.1" has unmet peer dependency "@testing-library/dom@>=5".
------
executor failed running [/bin/sh -c yarn -s]: exit code: 1
ERROR: Service 'web' failed to build : Build failed

**Comment by snazzysanoj** [comment]
@arifkyi There are a few dependency errors on the last commit. Can you try on this [commit](https://github.com/lucideus-repo/UnSAFE_Bank/commit/d4a157994f8ed01a828e60fc5db38b4e599ddc62) instead?

You can run the following to build from this particular commit
`git checkout d4a157994f8ed01a828e60fc5db38b4e599ddc62`
`docker-compose up -d`

**Comment by arifkyi** [comment]
Hello Snazzy Sanoj,

Supeeeer, it’s working now,

thank you so much.

Is it possible this commit to be in the main git clone ? just my humble opinion

Br,
Rifky

**Comment by snazzysanoj** [comment]
We're planning to update all dependencies to the latest and fix the broken ones soon

**Comment by arifkyi** [comment]
Hello Sanoj,
i hope you’re doing fine,
do we still need to run this?

git checkout d4a157994f8ed01a828e60fc5db38b4e599ddc62

or now can run from git clone ?
