### ISSUE TITLE
Map port 80 or 443 to Web server

### ISSUE THREAD

**Issue by mmesojedec** [lucideus-repo/UnSAFE_Bank#9]
Hi,

What is best option to map port 80 to Web server in your configuration and not map it to port 3000?
Which files needs to be changed in order to have backend accessible when this change is done?

Asking, because when I change some of the port mapping in the Dockerfiles and config files, and rebuild containers, I'm getting backend inaccessible message.

Is there anything else that needs to be done?

As well can SSL be enabled in the Web container, simply adding listening for port 443 and needed certificates on the NGNIX or there are some other mapping needed in the backend?

**Comment by DeepakPawar95** [comment]
Hi @mmesojedec,

You can change the mapping of the web application and backend port from 3000 and 80 respectively to any random port by changing the port mapping in `Backend/docker-compose.yml` file.
When you will change the Backend port from 80 to any other port, there are two options for you to make your backend accessible: 
1. **Permanent change:** Add the value of the new port in line 3 (initialization of `url` variable) of `Backend/web/src/app/config/config.ts` file. Once done, rebuild your image and container for the web.
2. **Temporary change:** Navigate to the application login page and complete the Test Connection process with the new port.

We currently don't have support for SSL for our web application.

**Comment by mmesojedec** [comment]
Hi @DeepakPawar95 

Thank you for reply.

You mean changing line like:

let ipAddress = localStorage.getItem("ipAddress");
let port = localStorage.getItem("port");
**let url = `http://${window.location.hostname}:8888/api`;**
if (ipAddress && port) url = "http://" + ipAddress + ":" + port + "/api";


And part of docker-compose.yml for web and server container for port mapping should look like:

  server:
    build: "./apache/"
    depends_on:
      - db
    networks:
      - backend
    **ports:
      - 8888:80**
    volumes:
      - ./src/:/var/www/html/

  web:
    build:
      context: "./web"
      dockerfile: Dockerfile
    depends_on:
      - server
    networks:
      - frontend
    **ports:
      - 80:8888**
  

Or I'm wrong and changing wrong parameters?

Actually when not doing Permanent change (changing config.ts) and changing only ports in the docker-compose.yml, I can use port 80 when using Temporary change (Test connection process).

**Comment by dspawar** [comment]
Hi @mmesojedec,

The aforementioned `config.ts` looks good but the port-mapping in docker-compose.yml needs change.
Your mapping should look like this:

```
server:
build: "./apache/"
depends_on:
- db
networks:
- backend
ports:
- <Custom-Port-1>:80
volumes:
- ./src/:/var/www/html/

web:
build:
context: "./web"
dockerfile: Dockerfile
depends_on:
- server
networks:
- frontend
ports:
- <Custom-Port-2>:80
```

The value of Custom-Port-1 will go in the config.ts file.

Thanks,
Deepak Pawar

**Comment by DeepakPawar95** [comment]
Hi @mmesojedec,

The aforementioned config.ts looks good but the port-mapping in docker-compose.yml needs change.
Your mapping should look like this:

```
server:
build: "./apache/"
depends_on:
- db
networks:
- backend
ports:
- <Custom-Port-1>:80
volumes:
- ./src/:/var/www/html/

web:
build:
context: "./web"
dockerfile: Dockerfile
depends_on:
- server
networks:
- frontend
ports:
- <Custom-Port-2>:80
```

The value of Custom-Port-1 will go in the config.ts file.

Thanks,
Deepak Pawar

**Comment by mmesojedec** [comment]
Thank you for your help.
I thought I need to map differently in the docker-compose file.

**Comment by dspawar** [comment]
Closing the issue as the query is resolved.
